# Generated by Django 5.1.6 on 2025-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0002_userprofile_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
