# Generated by Django 5.1.5 on 2025-02-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0004_userprofile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='room_code',
        ),
    ]
