# Generated by Django 5.1.6 on 2025-03-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0004_room_status_alter_room_admin_alter_room_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usercard_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
