# Generated by Django 5.1.5 on 2025-02-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0005_remove_userprofile_last_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
