# Generated by Django 5.1.6 on 2025-03-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0005_userprofile_usercard_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='usercard_name',
        ),
    ]
