# Generated by Django 5.1.5 on 2025-02-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0006_remove_userprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
