# Generated by Django 5.1.5 on 2025-02-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0007_remove_userprofile_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
