# Generated by Django 5.1.6 on 2025-03-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0008_room_is_expired_room_max_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_users',
        ),
    ]
