# Generated by Django 5.1.5 on 2025-02-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0008_userprofile_google_name_userprofile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='room_code',
        ),
    ]
