# Generated by Django 5.1.6 on 2025-02-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0009_remove_userprofile_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
