# Generated by Django 5.1.6 on 2025-02-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0010_userprofile_is_online_userprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='room_code',
        ),
    ]
